// Turns the design system's tokens.json into CSS custom properties, and copies
// the design system's component CSS without its Google Fonts import (the site
// self-hosts both fonts). Run automatically before `dev` and `build`.
// Source of truth: src/design-system/ (copied from the Morgan Smith design system).
import { readFileSync, writeFileSync } from "node:fs";

const ds = new URL("../src/design-system/", import.meta.url);
const out = new URL("../src/styles/", import.meta.url);
const t = JSON.parse(readFileSync(new URL("tokens.json", ds), "utf8"));

const lines = [];
for (const c of t.color.tokens) lines.push(`  --${c.name}: ${typeof c.value === "string" ? c.value : c.value.light};`);
for (const [k, v] of Object.entries(t.type.families)) lines.push(`  --font-${k}: ${v};`);
for (const fam of ["spacing", "radius"]) for (const s of t[fam].tokens) lines.push(`  --${s.name}: ${s.value};`);
for (const g of t.type.groups) for (const s of g.styles) {
  lines.push(`  --type-${s.name}-size: ${s.fontSize};`);
  lines.push(`  --type-${s.name}-line: ${s.lineHeight};`);
  lines.push(`  --type-${s.name}-weight: ${s.fontWeight};`);
}

writeFileSync(new URL("tokens.css", out),
  `/* Generated by scripts/build-tokens.mjs from src/design-system/tokens.json. Do not edit. */\n:root {\n${lines.join("\n")}\n}\n`);

const bundle = readFileSync(new URL("bundle.css", ds), "utf8").replace(/^@import[^\n]*\n/m, "");
writeFileSync(new URL("ds-components.css", out),
  `/* Generated by scripts/build-tokens.mjs from src/design-system/bundle.css. Do not edit. */\n${bundle}`);
console.log("tokens.css and ds-components.css written");
